### PR TITLE
Added Rebin's Blog feed

### PR DESCRIPTION
**Pull request by rebinqadirdev**

### CODE REVIEW

**Comment by madskristensen** [comment]
Did you mean to send this pull request?

**Comment by rebinqadirdev** [comment]
Just I meant to add only my personal blog feed into .NET Bytes Feed that organized by @CalvinAllen

**Comment by CalvinAllen** [comment]
@rebiiin You’ll want to fork the @dotnetbytes/friends-feed repo and submit a PR there.  I’ve made a lot of changes to the project that aren’t in @madskristensen upstream.

If you need help, just submit an issue on that repo with your twitter handle and rss link and I’ll make the changes.

**Comment by rebinqadirdev** [comment]
@CalvinAllen thank you.
Yes just I wanted add my blog feed.

**Comment by CalvinAllen** [comment]
@rebiiin I added you to the dotnetbytes repo directly, so you can close / abandon this PR.

Sorry for the noise, @madskristensen

**Pull request closed without merging**
